# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpsabXyBTP-nKAPGoGKyWQmZv2jh4H_O
"""

def calculator():
    print("Kalkulyator dasturiga xush kelibsiz!")
    print("Quyidagi operatsiyalarni tanlashingiz mumkin: +, -, *, /")

    # Foydalanuvchidan operatsiya va sonlarni qabul qilish
    operation = input("Operatsiyani kiriting (+, -, *, /): ")
    try:
        num1 = float(input("Birinchi sonni kiriting: "))
        num2 = float(input("Ikkinchi sonni kiriting: "))
    except ValueError:
        print("Xato! Faqat son kiriting.")
        return

    # Operatsiyaga qarab natijani chiqarish
    if operation == "+":
        print(f"Natija: {num1} + {num2} = {num1 + num2}")
    elif operation == "-":
        print(f"Natija: {num1} - {num2} = {num1 - num2}")
    elif operation == "*":
        print(f"Natija: {num1} * {num2} = {num1 * num2}")
    elif operation == "/":
        if num2 != 0:
            print(f"Natija: {num1} / {num2} = {num1 / num2}")
        else:
            print("Xato! Nolga bo'lish mumkin emas.")
    else:
        print("Xato! Noto'g'ri operatsiya kiritildi.")

# Dastur ishga tushiriladi
calculator()